const menu = {
    list() {
        return [
    {
        "backMenu":[
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
    {
        "backMenu":[
			{
                "child":[
                    {
						"appFrontIcon":"cuIcon-form",
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"健康上报",
                        "menuJump":"列表",
                        "tableName":"gerentizheng"
                    }
                ],
                "menu":"健康上报"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-activity",
                        "buttons":[
                            "查看"
                        ],
                        "menu":"公告信息",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"公告信息"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-goods",
                        "buttons":[
                            "查看",
                        ],
                        "menu":"健康科普",
                        "menuJump":"列表",
                        "tableName":"kepuzhishi"
                    }
                ],
                "menu":"健康科普"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-favor",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"科普收藏",
                        "menuJump":"列表",
                        "tableName":"kepuzhishiCollection"
                    }
                ],
                "menu":"科普收藏"
            }
            ,
            {
                "child":[
                    {
						"appFrontIcon":"cuIcon-evaluate",
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"科普留言",
                        "menuJump":"列表",
                        "tableName":"kepuzhishiLiuyan"
                    }
                ],
                "menu":"科普留言"
            }
        ],
        "frontMenu":[
        ],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"是",
        "hasFrontRegister":"是",
        "roleName":"用户",
        "tableName":"yonghu"
    }
]

	}
}
export default menu;
